@startuml "RegistrarRecepcionDeBolsin"
skinparam sequenceParticipant underline
skinparam participant {
    RoundCorner 150
}

actor ":EB" as EB

boundary ":BoundaryRegistrarRecepcionBolsin" as Boundary
control ":ControllerRegistrarRecepcionBolsin" as Controller
entity "activa:Sesion" as Sesion
entity "activo:Usuario" as Usuario
entity "logueado:Empleado" as Empleado
entity ":ComisionMedica" as ComisionMedica
entity ":Bolsin" as Bolsin
entity ":CambioEstadoBolsin" as CambioEstadoBolsin
entity "actual:CambioEstadoBolsin" as ActCambioEstadoBolsin
entity "nuevo:CambioEstadoBolsin" as NewCambioEstadoBolsin
entity ":Estado" as Estado
entity "seleccion:Bolsin" as BolsinSelecciondo
entity ":Remito" as Remito
entity ":DetalleRemito" as DetalleRemito
entity ":Documentacion" as Documentacion
entity ":TipoDocumento" as TipoDocumento
entity ":CambioEstadoDocumentacion" as CambioEstadoDocumentacion
entity "nuevo:CambioEstadoDocumentacion" as NewCambioEstadoDocumentacion

participant "<plain>29 Notificar recepción de bolsín</plain>" as CUNotificar

EB --> Boundary ** : opcionRegistrarBolsin()
Boundary -> Boundary : habilitarPantalla()

Boundary --> Controller ** : opcionRegistrarBolsin()

Controller -> Controller : getCMUsuarioLogueado()
Controller -> Sesion : getCMUsuarioLogueado()
Sesion -> Usuario: getEmpleado()
Usuario -> Empleado: getCM()
Empleado -> ComisionMedica : getNombre()

Controller -> Boundary : mostrarCMUsuario()

Controller -> Controller : obtenerBolsinesCMUsuario()
loop Mientras hayan bolsines
    Controller -> Bolsin : esTuCMOrigen()
    Controller -> Bolsin : sosEnviado()
    Bolsin -> CambioEstadoBolsin : sosActual()*
    Bolsin -> ActCambioEstadoBolsin : sosEnviado()
    ActCambioEstadoBolsin -> Estado : esEnviado()
end

Controller -> Boundary : mostrarBolsines()

EB -> Boundary : seleccionarBolsin()
Boundary -> Controller : tomarSeleccionBolsin()

Controller -> Controller : obtenerInformacionRemito()
Controller -> BolsinSelecciondo : obtenerInformacionRemito()
loop mientras haya remitos
    BolsinSelecciondo -> Remito : getDatosRemito()
    Remito -> Remito : getNumero()
    Remito -> Remito : mostrarDocumentacionIncluida()
    
    loop mientras haya detalles remitos
        Remito -> DetalleRemito : mostrarDocumentacion()
        DetalleRemito -> Documentacion : getDatosDocumentacion()
        Documentacion -> Documentacion : getAsuntoDocumentacion()
        DetalleRemito -> Documentacion : getTipoDocumentacion()
        Documentacion -> TipoDocumento : getNombre()
    end
end

Controller -> Boundary : mostrarDetalleBolsin()
Controller -> Boundary : mostrarOpcionesRecepcionBolsin()

EB -> Boundary : seleccionaOpcionContenidoCoincide()
Boundary -> Controller : tomarOpcionRecepcion()

Controller -> Boundary : pedirConfirmacion()

EB -> Boundary : confirmar()
Boundary -> Controller : confirmarRecepcion()

Controller -> Controller : RegistrarReepcion()
loop mientras haya estados
    Controller -> Estado : esAmbitoBolsin()
    Controller -> Estado : esRecibidoENCMDestino()
end
loop mientras haya estados
    Controller -> Estado : esAmbitoRemito()
    Controller -> Estado : esRecibidoYAceptado()
end
loop mientras haya estados
    Controller -> Estado : esAmbitoDocumentacion()
    Controller -> Estado : esRecibidoYAceptada()
end

Controller -> Controller : getFecha()

Controller -> BolsinSelecciondo : actualizarEstado()
BolsinSelecciondo -> ActCambioEstadoBolsin : setFechaHoraFin()
BolsinSelecciondo --> NewCambioEstadoBolsin** : new()

BolsinSelecciondo -> BolsinSelecciondo : actualizarEstadoRemito()

loop por cada remito del bolsín

    BolsinSelecciondo -> Remito : setEstado()
    Remito -> Remito : actualizarEstadoDoc()

    loop por cada documentación del remito
        Remito -> DetalleRemito : actualizarEstadoDoc()
        DetalleRemito -> Documentacion : setEstado()
        Documentacion -> CambioEstadoDocumentacion : sosActual()*
        Documentacion -> CambioEstadoDocumentacion : setFechaHoraFin()
        Documentacion --> NewCambioEstadoDocumentacion** : new()
    end
end
Controller -> Controller : llamarCu29NotificarRecepcionBolsin()
Controller -> CUNotificar : <<include>>

Controller -> Boundary : informarEjecucionExitosa()

Controller -> Controller : finCU()

@enduml