@startuml "Maquina de estado del Bolsin"
hide empty description

[*] --> Creado : new()
Creado -> Creado : agregarRemitos()
Creado -> DeBaja : eliminar()
Creado --> Cerrado : cerrar()

Cerrado -> Creado : romperPrecinto()
Cerrado -> DeBaja : eliminar()
Cerrado --> PendienteDeRetiro : finJornadaLaboral()

PendienteDeRetiro -> Enviado : retirado()

state "Recibido en CM destino" as recibido
Enviado -> Recibido : recibir()

DeBaja -> [*]
Recibido -> [*]

note left of Creado #FFCCCC
    REVISAR
    Inicialmente este estado era EnPreparacion.
    Luego de leer las ERS se interpretó que:
      - Es el estado inicial real
      - Aún no hay armado de bolsín
    Se renombra a Creado.
    Está correcta la interpretación?
end note

@enduml
