@startuml "Maquina de estado del Bolsin"
hide empty description

[*] --> Creado : new()
Creado -> Creado : agregarDocumentacion()
Creado --> EnBolsinSaliente : agregarABolsin()
Creado --> Cancelado : cancelar()

EnBolsinSaliente -> Creado : quitarDeBolsin()
EnBolsinSaliente --> EnBolsinEnviado : retirarBolsin()

state "RecibidaYAceptada" as RecYAcep
state "RecibidoYAceptadoParcial" as RecYAcepParc

EnBolsinEnviado --> RecYAcep : recibir()
EnBolsinEnviado ---> RecYAcepParc : recibir()

RecYAcep -> [*]
RecYAcepParc -> [*]

Cancelado -> [*]



@enduml

