@startuml "RegistrarRecepcionDeBolsin"

class BoundaryRegistrarRecepcionBolsin <<boundary>> {
  lblCMUsuario
  bolsinesEntrantes
  grdBolsinSeleccionado
  grdRemitos
  rdBtnOpcionesRecepcionBolsin
  btnConfirmarRecepcion
  ModalEjecucionExitosa
  opcionRegistrarBolsin()
  habilitarPantalla()
  mostrarCMUsuario()
  mostrarBolsines()
  seleccionarBolsin()
  mostrarDetalleBolsin()
  mostrarOpcionesRecepcionBolsin()
  seleccionaOpcionContenidoCoincide()
  pedirConfirmacion()
  confirmar()
  informarEjecucionExitosa()
}

class ControllerRegistrarRecepcionBolsin <<control>> { 
  estados
  sesionActiva
  empleadoLogueado
  cmUsuarioLogueado
  bolsinesEntrantes
  bolsinSeleccionado
  cambioEstadoActualBolsinSeleccionado
  remitosDelBolsinSelecionado
  opcionesRecepcionBolsin
  opcionesRecepcionBolsinSeleccionada
  confirmarRecepcion
  estadoBolsinRecibidoENCMDestino
  estadoRemitoRecibidoYAceptado
  estadoDocumentacionRecibidaYAceptada
  fechaHoraActual
  ejecucionExitosa
  obtenerBolsinesCMUsuario()
  opcionRegistrarBolsin()
  tomarSeleccionBolsin()
  tomarOpcionRecepcion()
  confirmarRecepcion()
  llamarCu29NotificarRecepcionBolsin()
  finCU()
}

class Sesion <<entity>> {
  fechaInicio
  fechaFin
  getCMUsuarioLogueado()
}

class Usuario <<entity>> {
  nombre
  contraseña
  getEmpleado()
}

class Empleado <<entity>> {
  apellido
  email
  nombre
  esTuCM()
  getCM()
  getEmail()
  mostrarCM()
  sosGCM()
}

class ComisionMedica <<entity>> {
  codigo
  direccion
  email
  nombre
  telefono
  getNombre()
}

class Bolsin <<entity>> {
  fecha
  numeroBolsin
  numeroPrecinto
  peso
  asociarRemito()
  crearCEBolsin()
  esTuCMOrigen()
  getNroPrecinto()
  getNumeroBolsin()
  mostrarDatos()
  new()
  obtenerCMDestino()
  esTuCMDestino()
  obtenerInformacionRemito()
  setDetalleBolsin()
  sosEnviado()
  actualizarEstado()
  actualizarEstadoRemito()
}

class Remito <<entity>> {
  fecha
  numero
  actualizarEstadoDoc()
  buscarDocumentacion()
  estasGenerado()
  getDatosRemito()
  getNumero()
  modificarDocumentacionIncluida()
  mostrarInformacionRemito()
  new()
  setEstado()
  tenesEstaCMDestino()
  tenesEstaCMOrigen()
  tomarDocumentacion()
}

class CambioEstadoBolsin <<entity>> {
  fechaHoraFin
  fechaHoraInicio
  new()
  setFechaHoraFin()
  sosActual()
  sosEnviado()
}

class Estado <<entity>> {
  ambito
  descripcion
  nombre
  esAmbitoBolsin()
  esAmbitoDocumentacion()
  esAmbitoRemito()
  esEnviado()
  esRecibidaYAceptada()
  esRecibidoENCMCDestino()
  esRecibidoYAceptado()
  getAmbito()
  getDescripcion()
  getNombre()
  new()
  setAmbito()
  setDescripcion()
  setNombre()
}

class Documentacion <<entity>> {
  asunto
  fechaPase
  numero
  aceptar()
  crearCE()
  getAsunto()
  getDatosDocumentacion()
  mostrarTipoDocumentacion()
  new()
  remitar()
  setEstado()
  incluirEnRemito()
  cancelarRemito()
  agregarABolsin()
  quitarDeBolsin()
  retirarBolsin()
  docNoRecibida()
  recibirYRechazar()
  redirigir()
  reenviarDocumentacion()
  eliminarDocumentacion()

}

class TipoDocumento <<entity>> {
  descripcion
  nombre
  getDescripcion()
  getNombre()
  new()
  setDescripcion()
  setNombre()
}

class Rol <<entity>> {
  descripcion
  nombre
  esGCM()
}

class DetalleRemito <<entity>> {
  areaCMCDestino
  aceptarDocumentacion()
  actualizarEstadoDoc()
  getDocumentacion()
  mostrarDocumentacion()
}


class CambioEstadoDocumentacion <<entity>> {
  fechaHoraFin
  fechaHoraInicio
  new()
  setFechaHoraFin()
  sosActual()
}

BoundaryRegistrarRecepcionBolsin ..> ControllerRegistrarRecepcionBolsin
ControllerRegistrarRecepcionBolsin ..> BoundaryRegistrarRecepcionBolsin

ControllerRegistrarRecepcionBolsin ..> Sesion
Sesion --> "1" Usuario
Empleado --> "1" Usuario
Usuario ..> Empleado
ControllerRegistrarRecepcionBolsin ..> Bolsin

ComisionMedica "1" <-- Empleado : asignadoA
Empleado --> "1" Rol : rol

Documentacion --> "1" TipoDocumento : tipoDocumento
Documentacion --> "1" ComisionMedica : cmOrigen
Documentacion --> "1..*" CambioEstadoDocumentacion : cambioEstado
CambioEstadoDocumentacion --> "1" Estado : estado
CambioEstadoDocumentacion --> "1" Empleado : responsableCE

Remito o--> "1..*" DetalleRemito : detalleRemito
DetalleRemito --> "1" Documentacion : documentacion
Remito --> "1" ComisionMedica : origen
Remito --> "1" ComisionMedica : destino
Remito --> "1" Estado : estado

Bolsin o--> "1..*" Remito : remito
Bolsin --> "1" ComisionMedica : origen
Bolsin --> "1" ComisionMedica : destino
Bolsin --> "1..*" CambioEstadoBolsin : cambioEstado
CambioEstadoBolsin --> "1" Estado : estado
CambioEstadoBolsin --> "1" Empleado : responsableCE

@enduml